### ISSUE TITLE
Plans for advanced LaTeX support?

### ISSUE THREAD

**Issue by RaitoBezarius** [miyuchina/mistletoe#1]
Hi there!

I am also looking to a good solution to write Markdown + LaTeX (preferably, with custom macros and environments) on static blog generator, for now, I have been using a mixture of [pandoc](pandoc.org) and MathJaX.

But I believe your idea could lead to something a lot more cleaner, do you think it'd be feasible [1] to add support for:

- `\def`, `\newcommand`, and so on.
- environments
- local packages (`amsthm`, `mathtools`, etc…)

Thank you for your time and your project, that's awesome!

[1]: Meaning that anyone could contribute a PR to do this.

**Comment by miyuchina** [comment]
I love the idea. And yes, complete LaTeX support is definitely a thing I will be aiming for down the road.

The main hurdle for this, as I see it, is that as of this moment mistletoe only supports LaTeX elements *when rendering to LaTeX*. A current working example is LaTeX's inline math elements.

If I understand your proposal correctly, you seem to want LaTeX elements to be rendered into HTML. I also have this goal in mind, but doing so would involve some important design changes, of which I am not sure of the implications. Not saying that this can't be done -- I will probably open a branch and see what I can do -- but it certainly involves some careful planning.

Some random thoughts:

* We should probably look into what [mobiledoc](https://github.com/bustle/mobiledoc-kit) has been doing, esp. with [cards](https://github.com/bustle/mobiledoc-kit/blob/master/CARDS.md) (rich block-level elements) and [atoms](https://github.com/bustle/mobiledoc-kit/blob/master/ATOMS.md) (rick span-level elements).

    This is probably the biggest design question, as it offers a unified interface for future custom elements.

* mistletoe should learn to read from its own AST, so that we can store documents as JSON and retrieve it later (this one should be easy).

    This is relevant because we need to figure out a way to store custom elements, e.g. LaTeX environments, macros and such.

* We probably need some javascript to render LaTeX elements at some point, so the question is to design an API for javascript robust enough that makes the lives of future adventurers easier.

    The easiest way to do this is probably just embed the necessary javascript into rendered HTML. Maybe we can get that working before coming up with a cleaner solution.

Once we somewhat figure out the previous points, I think we'll get a better idea of how we can work towards supporting the features you mentioned. I'll keep this issue open to see what others think of it.

> Meaning that anyone could contribute a PR to do this

... by all means, *please* hack around, give a feature example and open a PR.

Thanks for this!

**Comment by miyuchina** [comment]
Well it's actually easier than I expected. Take a look at the [mathjax](https://github.com/miyuchina/mistletoe/blob/master/plugins/mathjax.py) module under `plugins`: it should provide some rudimentary support for MathJax's syntax.

If you want math enclosed in parenthesis or brackets, you need to escape it twice: `\\(1 + 1 = 2\\)`. Similarly with `\def` or macros:

```tex
```
