### ISSUE TITLE
Update to CommonMark v0.30

### ISSUE THREAD

**Issue by enderger** [miyuchina/mistletoe#108]
Recently, the CommonMark spec got an update. While the project may be inactive, if an update was awaiting the spec now is the time to do it.

**Comment by pbodnar** [comment]
OK, I've just checked against v0.30 and 20 tests of 652 are failing. It will be quite a job to get all fixed, I guess. Any volunteers? :)

This is how to download new spec and run tests against it:

1) Change `VERSION` in "test/specification/spec.sh".
2) Run in bash:

```
$ cd test/specification
$ ./spec.sh
...
$ cd ../..
$ python -m test.specification
```

**Comment by pbodnar** [comment]
About to be fixed by: #156.

**Comment by anderskaplan** [comment]
Example 28 fails because HTML5 entities without a trailing semicolon (such as &copy) are explicitly not allowed by the CommonMark spec, but mistletoe uses the python function `html.unescape()` under the hood, which *does* recognize them.

This is a case where it can be argued whether spec compliance is an improvement, or not. Thoughts?

I certainly see the value in spec compliance, but I'll wait with fixing this anyway to give some time for discussion.

**Comment by pbodnar** [comment]
> Example 28 fails because HTML5 entities without a trailing semicolon (such as &copy) are explicitly not allowed by the CommonMark spec, but mistletoe uses the python function `html.unescape()` under the hood, which _does_ recognize them.
> 
> This is a case where it can be argued whether spec compliance is an improvement, or not. Thoughts?
> 
> I certainly see the value in spec compliance, but I'll wait with fixing this anyway to give some time for discussion.

Well, I have tested and it seems like in fact mistletoe is already pretty close to spec compliance - this is the output from the failed test:

```
example:  28
markdown: '&nbsp &x; &#; &#x;\n&#87654321;\n&#abcdef0;\n&ThisIsNotDefined; &hi?;\n'
html:     '<p>&amp;nbsp &amp;x; &amp;#; &amp;#x;\n&amp;#87654321;\n&amp;#abcdef0;\n&amp;ThisIsNotDefined; &amp;hi?;</p>\n'
output:   '<p>&amp;nbsp &amp;x; &amp;#; &amp;#x;\n�\n&amp;#abcdef0;\n&amp;ThisIsNotDefined; &amp;hi?;</p>\n'
```

So it looks like we should just simply _add limits on number of digits_ to _existing_ replacement of `html`'s regex search inner field, to satisfy the CommonMark spec (now `&#87654321;` gets otherwise-correctly replaced by so called replacement char `U+FFFD`; this was added to the compliance example in spec v0.29, while also changing max number of digits - see [spec](https://spec.commonmark.org/0.30/#decimal-numeric-character-references)):

```diff
diff --git a/mistletoe/html_renderer.py b/mistletoe/html_renderer.py
index 3f5a60d..2625adc 100644
--- a/mistletoe/html_renderer.py
+++ b/mistletoe/html_renderer.py
@@ -29,8 +29,8 @@ class HTMLRenderer(BaseRenderer):
         # html.entities.html5 includes entitydefs not ending with ';',
         # CommonMark seems to hate them, so...
         self._stdlib_charref = html._charref
-        _charref = re.compile(r'&(#[0-9]+;'
-                              r'|#[xX][0-9a-fA-F]+;'
+        _charref = re.compile(r'&(#[0-9]{1,7};'
+                              r'|#[xX][0-9a-fA-F]{1,6};'
                               r'|[^\t\n\f <&#;]{1,32};)')
         html._charref = _charref
```

@anderskaplan, maybe you have tested with an altered mistletoe version, or maybe you have overlooked this?

And of course, once again, as discussed recently elsewhere, it is questionable whether we shouldn't move this code, so that it is available for all renderers and not just for the HTML renderer...

Thoughts? I think doing just the change suggested above could suffice for now.

**Comment by anderskaplan** [comment]
Ok, I see. No, I wasn't aware of this workaround. I started from a test case and invoked span_token.tokenize_inner() directly, so the workaround in the HTMLRenderer wasn't included.

Imho the HTMLRenderer isn't a great place for the workaround. Mainly because it won't be available to other renders that way, meaning they will behave differently, and also because it seems more related to parsing than rendering to me.

I'll try to come up with a solution both for the failing case and for a more generic workaround.

**Comment by anderskaplan** [comment]
Updated the PR to include this fix.

**Comment by pbodnar** [comment]
@anderskaplan, OK, agreed, go for it. :) I guess moving the "workaround" regex code into the `BaseRenderer` class could suffice, but you'll see. Thank you.

Technical note: It would generally help me - for better orientation when switching among PR branches - if you could put a short description into the branches' names, e.g. `fix-108-char-refs-digit-limit` for this one. :)

**Comment by pbodnar** [comment]
> Updated the PR to include this fix.

Thank you, so PR #165 - no need to create a new PR / branch this time.

**Comment by pbodnar** [comment]
Hopefully all clean now, closing as resolved. :) Big thanks to @anderskaplan. :)
