### ISSUE TITLE
Footnote not processed if there is a whitespace in text

### ISSUE THREAD

**Issue by nsarang** [miyuchina/mistletoe#216]
Hi folks,
I've encountered an issue where footnote tokens aren't properly tagged if there is any white space in the text.

# Example
```python
from mistletoe import block_token

lines = '''
[^1]: Works
[^2]: Not working
'''
token = block_token.Document(lines)
print(token.footnotes)
```

outputs:
```
{'^1': ('Works', '')}
```

While removing the space produces:
```
{'^1': ('Works', ''), '^2': ('Notworking', '')}
```

**Comment by pbodnar** [comment]
@nsarang, thanks for the report. The actual problem is that mistletoe doesn't support _footnotes_ in the form as for example GitHub here supports them -> see #47 for the feature request.

Instead, mistletoe only supports so called _link reference definitions_ as described in the CommonMark Spec: https://spec.commonmark.org/0.30/#link-reference-definitions. That's why `[^2]: Not working` is treated as a plain text - because it matches the case from spec's [Example 209](https://spec.commonmark.org/0.30/#example-209). Historically, mistletoe uses term "footnotes" for these, which I admit might be confusing...

**Comment by nsarang** [comment]
Thanks for the clarification @pbodnar
