### ISSUE TITLE
List parsing requests

### ISSUE THREAD

**Issue by huettenhain** [miyuchina/mistletoe#34]
Hello again, and thanks one more time for this great tool. I am having some minor troubles with bullet point lists; consider the following Markdown:

```
First List
- this is
- the first list
  - and this is
  - its sublist
- moving on.
  
Second List

- this is
- the second list
  - and this is
  - its sublist
- moving on.

Third List

- this is
- the third list
    - and this is
    - its sublist
- moving on.
```

You will notice that only the third list is parsed as intended by Mistletoe: 

1. The first one is not parsed at all because (I think) it is not preceded by a paragraph
2. The sublist of the second list is not recognized because it looks like 4 spaces of indentation are required.

I would prefer if any new level of indentation would be recognized as starting a sublist, and it would be great if a new paragraph was not required before a bullet point list.

**Comment by miyuchina** [comment]
Ah, I might have to fix it over the weekend, since my hands are a bit tied with work. And yes, the reasons you gave are correct.

Preliminary thoughts about (2): CommonMark does not allow less than 4 spaces of indent, and GitHub does not allow less than 2. I'm leaning towards following the GFM convention here, and not allowing only 1 space before sublists. There could be lazy-continuation lines that start with a space (they shouldn't do that, but one space also does not give enough visual cue that the current line is in a sublist.)

What do you think?

**Comment by huettenhain** [comment]
If you want, I can try and make a PR for this, I just always feel like you can fix stuff much quicker ;-). 

Regarding 2: I completely agree that it is unnecessary to recognize single space indent for new sublists. I am somewhat biased here since I would really like 2 space indent to work, and I find it visually appealing when editing the Markdown source. However, let me also say that if you want to enforce CommonMark, that would be completely legitimate and understandable.

**Comment by miyuchina** [comment]
This is taking me longer to fix because lists are complicated to parse :disappointed: Will report back with hopefully more cheerful news, but I am definitely working on both requests.

Thanks for the patience!

**Comment by huettenhain** [comment]
Again, I can only stress how grateful I am for the library and your quick response to requests. Please don't worry and take your time. Thanks again!

**Comment by miyuchina** [comment]
Should be fixed! Two spaces or more makes a sublist. Will include in the next release (I'm thinking some time around end of this month?)
