### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by sglyon** [miyuchina/mistletoe#5]
Sorry, I couldn't find a better place to leave this, but wanted to share my experience using the library nonetheless.

I used mistletoe to write a spell checker script for jupyter notebooks in about an hour! My script basically reads in the notebook, tokenizes all markdown cells with mistletoe, and then I have a custom renderer that only prints out a cell number followed by the misspelled words in that cell.

It was all very easy and runs efficiently, so nice work on a great library.

The one piece of constructive feedback I can offer is that I only got my custom tokens to be active during parsing if I force `MyRenderer.__enter__()` to be called (e.g. I use the renderer as a context manager). I don't remember seeing that pointed out in the README, and was only able to figure it out by reading the source for BaseRenderer.

**Comment by miyuchina** [comment]
No problem at all. Thank you for using mistletoe!

Per your feedback, I did two things in the dev branch:
- explained that renderers should be used as context managers (10f22fb);
- made custom tokens active without needing to call `MyRenderer.__enter__()` (02f1da9).

These will soon be merged into the master branch, and included in the next major version release.

Let me know if there are any other improvements (documentation or otherwise) that you would like to see!
