### ISSUE TITLE
Inline code results in surrounding emphasis being ignored

### ISSUE THREAD

**Issue by vallentin** [miyuchina/mistletoe#70]
If the first element within an emphasis is inline code, then the surrounding emphasis is ignored.

Case:

```markdown
*`foo` bar baz*
```

Result:

```html
<p>*<code>foo</code> bar baz*</p>
```

Desired Result:

```html
<p><em><code>foo</code> bar baz</em></p>
```

Searching in [CommonMark specification](https://spec.commonmark.org/0.28/) I wasn't able to find whether this was defined and intended or a bug.

This does however deviate from how Markdown is rendered on GitHub, Stack Overflow and in Visual Studio Code. *While also being something I needed.*

**Comment by pbodnar** [comment]
Thank you, confirmed. Moreover according to my tests, this happens not only for `*`, but also for `_` or `**`. The only "immune" one is `~~`, probably because unlike the former ones, this one is not parsed as a "core token".

**Comment by pbodnar** [comment]
Looking at this closely now...

Strangely enough, it looks like even the latest CommonMark spec ([txt](https://github.com/commonmark/commonmark-spec/commits/master/spec.txt)) doesn't seem to cover this very basic use case of having a simple *emphasized code span* like *`foo`*:

    *`foo`*

That's why running `make specification` doesn't find this error.

Anyway, it looks like I've found the culprit by debugging and I am going to fix this soon, even though this will be after 3 long years since this report...

**Comment by pbodnar** [comment]
OK, so hopefully fixed without any side effects (see commit above). :)
