### ISSUE TITLE
 Code Injection bug

### ISSUE THREAD

**Issue by find456789** [miyuchina/mistletoe#83]
1. download the file(https://github.com/cujanovic/Markdown-XSS-Payloads/blob/master/Markdown-XSS-Payloads.txt) rename to 123.md

2. run` mistletoe 123.md > out.html`

3. open `out.html`

![image](https://user-images.githubusercontent.com/6580897/58255517-bc10cb00-7d9f-11e9-81d1-3e0c8776b9ef.png)

how to fix it,

thank you very much

**Comment by miyuchina** [comment]
Thank you for this--I don't actually think, though, that it is up to the parser to strip user input of malicious content. Especially since mistletoe is written in Python, its output is less likely (than some JavaScript parsers, at least) to be hooked directly into a front-end. Stripping html tags, as discussed in #74, might be a possibility, but still cannot prevent XSS injections completely, and I don't feel capable doing a security audit of Markdown anyways.

This came up in my brief research of the topic, which might also be helpful: [Showdown](https://github.com/showdownjs/showdown/wiki/Markdown%27s-XSS-Vulnerability-(and-how-to-mitigate-it)), a JavaScript parser, recommends that users do XSS filtering *after* the Markdown parser has finished producing HTML.

Sorry I won't be able to fix this. I'll nevertheless add a note in the documentation about XSS injections, and I'll keep this issue open for now.

**Comment by pbodnar** [comment]
> Sorry I won't be able to fix this. I'll nevertheless add a note in the documentation about XSS injections, and I'll keep this issue open for now.

Just for a reference, it seems like this particular problem was actually not documented.
