### ISSUE TITLE
Inline code for tilde invalidly parsed as code block start

### ISSUE THREAD

**Issue by liushilive** [miyuchina/mistletoe#91]
## The sample code

```
* `~` home
```

## analytical result

![image](https://user-images.githubusercontent.com/13434707/68274490-3dd18800-00a4-11ea-8358-db51e7b0335f.png)

**Comment by pbodnar** [comment]
This seems easy to fix - the regex pattern needs to accept either just backticks, or just tildes. The linked fix seems a little bit more complicated though...

**Comment by pbodnar** [comment]
OK, so I fixed it this in the master.

Note that there is still another bug, possibly also in the linked patch from @chrisjsewell, which incorrectly rejects a fenced code block like this:

```
~~~ lang myextra_params_containing_~
code block
~~~
```

GitHub renders this correctly:

~~~ lang myextra_params_containing_~
code block
~~~

... because https://spec.commonmark.org/0.30/#info-string clearly states that:

> Info strings for tilde code blocks can contain backticks and tildes

**Comment by chrisjsewell** [comment]
Heya, I would just note that I moved on from mistletoe, since it didn't quite have the features I needed, and went on to create https://github.com/executablebooks/markdown-it-py (and port for the widely used markdown-it)

**Comment by pbodnar** [comment]
Hi Chris, yeah, I've already noticed very well when doing triage of opened issues and PRs here, and I wish you good luck with your project. :)
